<?php
<<<<<<< HEAD
// sets up autoloading, autoload.php is a file automatically
// generated by composer, it defines a hash table that uses
// class name as key and file path as value.
// And reigsters autoloading with spl_autoload_register (http://php.net/manual/en/function.spl-autoload-register.php )
//
// @see http://getcomposer.org/doc/01-basic-usage.md for detail usage
require 'Vendors/autoload.php';
=======
/**
 * Bootstrap file
 * 
 */


>>>>>>> 603668d43402aeaef47db24f2a49bd89423291c5
?>
